---
- hosts: all
  sudo: True
  tasks:
  - apt: name=$item state=latest
    with_items:
     - httpd
     - python-mysqldb
     - mysql-server
     - nginx 
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - yum: name=$item state=latest
    with_items:
     - httpd
     - python-mysqldb
     - mysql-server
     - nginx
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

  - service: name=$item state=started enabled=yes
    with_items:
     - httpd
     - python-mysqldb
     - mysql-server
     - nginx 
